language: python
sudo: required
services:
- docker
before_install:
- cat ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_254fbb7fb5b5_key -iv $encrypted_254fbb7fb5b5_iv
  -in deploy_key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa*
- eval `ssh-agent -s`
- ssh-add ~/.ssh/id_rsa
- sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty-backports universe'
- sudo apt-get update -qq
- sudo apt-get install -y -o Dpkg::Options::="--force-confold" --force-yes docker-engine
install:
- pip install git+https://github.com/ansible/ansible-container.git
- pip install ansible
script:
- mkdir build
- git clone git@github.com:masschallenge/impact-api.git build
- mv ansible build
- cd build
- ansible-container build

