---

- name: install gcc
  apt:
    name: gcc
    state: latest
    update_cache: yes

- name: install python-virtualenv
  apt:
    name: python-virtualenv
    state: latest

- name: install mysql-client
  apt:
    name: mysql-client
    state: latest

- name: install netcat
  apt:
    name: netcat
    state: latest

- name: install rsync
  apt:
    name: rsync
    state: latest

- name: upgrade pip
  command: pip install --upgrade pip

- name: install virtualenv
  command: pip3 install virtualenv --upgrade

- name: Make Django user
  user:
    name: "{{ DJANGO_USER }}"
    uid: 1000
    group: root
    state: present
    createhome: yes
    home: "/wwwroot/home"

- name: Change /django permissions
  file:
    path: "{{ DJANGO_ROOT }}"
    state: directory
    owner: "{{ DJANGO_USER }}" 
    group: root
    mode: 0775

- name: Copy source
  synchronize:
    src: "{{ lookup('pipe','dirname `pwd`') }}/web/impact/requirements"
    dest: "{{ DJANGO_ROOT }}/requirements"
  remote_user: "{{ DJANGO_USER }}"

- name: Install requirements
  pip:
    requirements: "{{ DJANGO_ROOT }}/requirements/{{DEPLOYMENT}}.txt"
  remote_user: "root"

- name: Copy entrypoint
  copy:
    src: "{{ role_path }}/files/{{ item }}" 
    dest: "/usr/bin/{{ item }}"
    owner: root
    group: root
    mode: 0775
  with_items:
    - entrypoint.sh
