version: '2'
defaults:
  DEPLOYMENT: dev
  DJANGO_CONFIGURATION: Dev
  DJANGO_SECRET_KEY: d60a10fc-ffb7-4798-89c3-b28aa06d8659
  DJANGO_HIREDIS_CACHE_LOCATION: redis:6379
  DJANGO_ALLOWED_HOSTS: ""
  DATABASE_URL: mysql://root:root@mysql/mc_dev
  EMAIL_URL: console://
  MYSQL_PASSWORD: root
  MYSQL_DATABASE: mc_dev
  DATA_SOURCE_ENDPOINT: sqlite:////wwwroot/impact//tests/sql/db.test.sqlite3
  WEB_USER: impact_user
  DJANGO_ROOT: /wwwroot/app
  DJANGO_VENV: /wwwroot/.venv
services:
  mysql:
    user: mysql
    image: mysql
    ports:
      - "3307:3306"
    volumes:
      - $PWD/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - $PWD/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: {{ MYSQL_PASSWORD }}
      MYSQL_DATABASE: {{MYSQL_DATABASE}}
      DJANGO_ROOT: '{{ DJANGO_ROOT }}'
      DJANGO_VENV: '{{ DJANGO_VENV }}'
    command: [ "mysqld"]
  # Redis
  redis:
    image: redis
    volumes:
      - $PWD/redis:/var/lib/redis/data
    command: ["redis-server"]
  # Nginx
  nginx:
    image: nginx
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - $PWD/web/impact/media:/media:ro
      - $PWD/web/impact/static:/static:ro
    links:
      - web
    dev_overrides:
      ports: []
      command: '/bin/false'
    environment:
      VIRTUAL_HOST: impact.dev
    command: ['nginx', '-c', '/etc/nginx/nginx.conf']
  # Assets
  assets:
    image: donnex/assets
    command: /bin/false
    ports:
      - "35729:35729"
    volumes:
      - ./assets/gulpfile.js:/gulp/gulpfile.js:ro
      - ./web/impact/sass:/gulp/sass
      - ./web/impact/static/css:/gulp/css
      - ./web/impact/static/js:/gulp/js
  # Web python
  web:
    image: "python:3.6"
    ports:
      - "8000:8000"
    volumes:
      - $PWD/web/impact:{{DJANGO_ROOT}}
    depends_on:
      - mysql
    links:
      - mysql
      - redis
    user: root
    environment:
      MYSQL_ROOT_PASSWORD: {{ MYSQL_PASSWORD }}
      MYSQL_DATABASE: {{MYSQL_DATABASE}}
      DATA_SOURCE_ENDPOINT: {{DATA_SOURCE_ENDPOINT}}
      DJANGO_CONFIGURATION: {{DJANGO_CONFIGURATION}}
      DJANGO_SECRET_KEY: {{DJANGO_SECRET_KEY}}
      DJANGO_HIREDIS_CACHE_LOCATION: {{DJANGO_HIREDIS_CACHE_LOCATION}}
      DJANGO_ALLOWED_HOSTS: {{DJANGO_ALLOWED_HOSTS}}
      DATABASE_URL: mysql://{{MYSQL_USER}}:{{MYSQL_PASSWORD}}@mysql/{{MYSQL_DATABASE}}
      EMAIL_URL: {{EMAIL_URL}}
      DJANGO_ROOT: {{DJANGO_ROOT}}
      DJANGO_VENV: {{DJANGO_VENV}}
    dev_overrides:
      environment:
        DEPLOYMENT: dev
        MYSQL_ROOT_PASSWORD: {{ MYSQL_PASSWORD }}
        MYSQL_DATABASE: {{MYSQL_DATABASE}}
        DATA_SOURCE_ENDPOINT: {{DATA_SOURCE_ENDPOINT}}
        DJANGO_CONFIGURATION: {{DJANGO_CONFIGURATION}}
        DJANGO_SECRET_KEY: {{DJANGO_SECRET_KEY}}
        DJANGO_HIREDIS_CACHE_LOCATION: {{DJANGO_HIREDIS_CACHE_LOCATION}}
        DJANGO_ALLOWED_HOSTS: {{DJANGO_ALLOWED_HOSTS}}
        DATABASE_URL: mysql://{{MYSQL_USER}}:{{MYSQL_PASSWORD}}@mysql/{{MYSQL_DATABASE}}
        EMAIL_URL: {{EMAIL_URL}}
    command: ["/bin/bash", '-c', "/usr/bin/entrypoint.sh"]
    
registries:
  production:
    url: 997386117669.dkr.ecr.us-east-1.amazonaws.com/masschallenge/impact
