- hosts: all
  gather_facts: no
  vars:
    docker_compose_version: 2
  tasks:
    - raw: apt-get update
    - raw: (which python && which aptitude) || apt-get install -y python python-apt aptitude
    - name: Upgrade APT                                                                                                                                                                                                                                      
      apt: upgrade=yes                                                                                                                                                                                                                                       
    - name: Install ca-certificates                                                                                                                                                                                                                          
      apt: name=ca-certificates state=latest                                                                                                                                                                                                                 
    - name: Install dumb init
      get_url:
        dest: /usr/bin/dumb-init
        url: https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64
        mode: 0775
        validate_certs: no

- hosts: web
  strategy: debug
  roles:
  - django-gunicorn
