---
DJANGO_USER: impact_user
DJANGO_ROOT: /wwwroot/app
DJANGO_STATIC_ROOT: /wwwroot/static-compiled
DEPLOYMENT: dev
DJANGO_VENV: /wwwroot/venv
DJANGO_ALLOWED_HOSTS: "*"
DATA_SOURCE_ENDPOINT: sqlite:////wwwroot/impact/tests/sql/db.test.sqlite3